### ISSUE TITLE
[enhancement] Seeding should follow .NET Core 2.0 best practice?

### ISSUE THREAD

**Issue by pjmagee** [TrilonIO/aspnetcore-angular-universal#507]
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/35c336b6625ccbef405804cb99303656720c9b90/Startup.cs#L69

Should be something along the lines of: https://github.com/aspnet/Home/issues/2188#issuecomment-327471217

Basically, seed data prior to running the site.

**Comment by MarkPieszak** [comment]
Definitely, I've unfortunately been beyond busy as I really need to get back to fixing the Prod & TransferState issue here, but I'll definitely try and fix up some of these when that's all settled! Thanks @pjmagee 👍
