### ISSUE TITLE
environment variables in Angualar

### ISSUE THREAD

**Issue by vmachacek** [TrilonIO/aspnetcore-angular-universal#588]
Can anyone please tell me how can I make environment variables work?

**Comment by Adondriel** [comment]
Depends on your definition of Environment variables... do you want something that is simply a global variable for all components? You should make a configService, to inject into each component that needs it. 

If you want actual PC env vars... I don't think angular has any way to get anything close to that... as it's entirely client side.

**Comment by vmachacek** [comment]
I was referring to environment variables as we know it from angular. I think angular cli / webpack takes care of bundling correct file, when you are building for test/production.

**Comment by Adondriel** [comment]
Ah, yes. we use webpack (unless things have changed) it should be the same
as anything else that uses webpack, assuming they have the documentation to
config that, that should be where to look.
