### ISSUE TITLE
Typescript package is 13 mb in main bundle

### ISSUE THREAD

**Issue by asadmalik3** [TrilonIO/aspnetcore-angular-universal#676]
Why we have to bundle typescript with angular? Can we remove it? it is consuming 13 mb. See screenshot below

![image](https://user-images.githubusercontent.com/6158094/44390745-e23cce00-a4e2-11e8-8be3-cfbdc7d8eb8d.png)

**Comment by MarkPieszak** [comment]
Are you looking at development mode perhaps?

**Comment by asadmalik3** [comment]
Yes i am looking at it on development mode.
What is the need of that package in development mode?

**Comment by MarkPieszak** [comment]
Mainly it's probably there for the sourcemaps so you can debug in the browser, etc. Once you're in Prod mode, typescript goes away since it'll all be compiled down to JS. Nothing to worry about though, development bundles are always big :)

**Comment by MarkPieszak** [comment]
Unfortunately no since we'll need it for sourcemaps etc
